# Site settings
title: VJ Patel
email: vj@vjpatel.me
description: > 
  Final year Computer Scientist at Queen Mary, University of London. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vjpatel.me" # the base hostname & protocol for your site
twitter_username: vjftw
github_username:  vjftw
timezone: Europe/London

# Build settings
markdown: kramdown
sass:
    style: :compressed