# Site settings
title: VJ Patel
email: vj@vjpatel.me
short_about: >
  I'm a final year Computer Scientist at Queen Mary, University of London who has taken a deep interest in Application Security, Cryptography and the Internet of Things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vjpatel.me" # the base hostname & protocol for your site
twitter_username: VJftw
github_username:  VJftw
linkedin_name: VJ Patel
linkedin_url: https://uk.linkedin.com/pub/vj-patel/6b/648/109
google_plus_name: VJ Patel
google_plus_url: https://google.com/+VJPatel1994
timezone: Europe/London

# Qualifications
qualifications:
    - name: Computer Science BSc with Industrial Experience
      year_range: 2012 - 2016
      institutions:
        - name: Queen Mary, University of London
          uri: http://www.qmul.ac.uk
          years:
            - name: Final Year
              year_range: 2015/16
              weight: 65
              credits: 120
              modules:
                - name: Project
                  credits: 30
                - name: Algorithms and Complexity
                  credits: 15
                - name: Embedded Systems
                  credits: 15
                - name: Advanced Database Systems and Technology
                  credits: 15
                - name: Distributed Systems and Security
                  credits: 15
                - name: Computability
                  credits: 15
                - name: Web Programming
                  credits: 15
            - name: Industrial Experience
              location: <a target="_blank" href="http://www.uvd.co.uk">Ultra Violet Design (UVD)</a>
              year_range: 2014/15
              score: 77.0
              weight: 7
              credits: 30
              modules:
                - name: Industrial Placement
                  score: 77.0
                  credits: 30
            - name: Second Year
              year_range: 2013/14
              score: 69.48
              weight: 28
              credits: 120
              modules:
                - name: Software Engineering
                  score: 73.4
                  credits: 15
                - name: Probability and Matrices
                  score: 59.3
                  credits: 15
                - name: Algorithms and Data Structures in an Object-Orientated Framework
                  score: 66.0
                  credits: 15
                - name: Internet Protocols and Applications
                  score: 67.4
                  credits: 15
                - name: Software Engineering Project
                  score: 94.0
                  credits: 15
                - name: Operating Systems
                  score: 64.7
                  credits: 15
                - name: Database Systems
                  score: 64.7
                  credits: 15
                - name: Graphical User Interfaces
                  score: 66.4
                  credits: 15
        - name: Hertfordshire University
          uri: http://www.herts.ac.uk
          years:
            - name: First Year
              year_range: 2012/13
              score: 89.125
              weight: 0
              credits: 120
              modules:
                - name: Programming Principles
                  score: 97.1
                  credits: 15
                - name: Foundations of Computation
                  score: 93.2
                  credits: 15
                - name: E-Media Design
                  score: 88.4
                  credits: 15
                - name: System Requirements
                  score: 83.2
                  credits: 15
                - name: Programming and Program Design
                  score: 91.4
                  credits: 15
                - name: Data Driven Systems
                  score: 87.4
                  credits: 15
                - name: Principles of Network Systems
                  score: 77.45
                  credits: 15
                - name: Internet Technologies
                  score: 88.25
                  credits: 15
                - name: Professional and Academic Skills
                  score: 73.6
                  credits: 0


# Build settings
markdown: kramdown
sass:
    style: :compressed
