# Site settings
title: VJ Patel
email: vj@vjpatel.me
short_about: >
  I'm an MSc Computing and Security student at King's College, London who explores Cryptography, Dev Ops and the Internet of Things.
long_about: >
  You can also find me lost in space <i class="fa fa-rotate-270 fa-space-shuttle"></i>, raving at a festival <i class="fa fa-music"></i> or buried in a book <i class="fa fa-book"></i>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vjpatel.me" # the base hostname & protocol for your site
twitter_username: VJftw
github_username:  VJftw
linkedin_name: VJ Patel
linkedin_url: https://uk.linkedin.com/pub/vj-patel/6b/648/109
google_plus_name: VJ Patel
google_plus_url: https://google.com/+VJPatel1994
timezone: Europe/London

projects:
  - name: Implementations of Homomorphic Encryption
    short_description: My BSc dissertation project that presents and runs different homomorphic encryption schemes
    url: /projects/homomorphic-encryption
    status: complete
  - name: Orchestrate
    short_description: A tool to manage Docker containers running on PaaS (AWS, GCP) focused on auto-scaling group
    url: /projects/orchestrate
    status: idle
  - name: Invoke Docker Flow
    short_description: A PyPi package for use with Docker containers and Python's Invoke task runner
    url: /projects/invoke-docker-flow
    status: in-progress
  - name: Raspberry Pi HUD
    short_description: Using a Raspberry Pi 3 and a touchscreen display to help improve productivity
    url: /projects/raspberry-pi-hud
    status: idle
  - name: Blog/Website
    short_description: CloudFlare + Jekyll + GitHub Pages
    url: /projects/website
    status: idle


# Qualifications
qualifications:
    - name: MSc Computing and Security
      year_range: 2016 - 2017
      institutions:
        - name: King's College London
          uri: http://www.kcl.ac.uk
          years:
            - name: The Year
              year_range: 2016/17
              weight: 100
              modules:
                - name: Individual Project
                  credits: 60
                - name: Cryptography and Information Security
                  credits: 15
                - name: Advanced Software Engineering
                  credits: 15
                - name: Security Engineering
                  credits: 15
                - name: Web Infrastructure
                  credits: 15
                - name: Computer Forensics and Cybercrime
                  credits: 15
                - name: Group Project
                  credits: 15
                - name: Network Security
                  credits: 15
                - name: Text Searching and Processing
                  credits: 15
    - name: BSc Computer Science with Industrial Experience
      year_range: 2012 - 2016
      award: 1<sup>st</sup> Class (Hons)
      score: 75.14
      institutions:
        - name: Queen Mary, University of London
          uri: http://www.qmul.ac.uk
          years:
            - name: Final Year
              year_range: 2015/16
              score: 77.37
              weight: 65
              credits: 120
              modules:
                - name: Dissertation Project (<a href="http://homomorphic-encryption.vjpatel.me" target="_blank">Implementations of Homomorphic Encryption</a>)
                  score: 81.9
                  credits: 30
                - name: Algorithms and Complexity
                  score: 73.2
                  credits: 15
                - name: Embedded Systems
                  score: 83.4
                  credits: 15
                - name: Advanced Database Systems and Technology
                  score: 70.4
                  credits: 15
                - name: Distributed Systems and Security
                  score: 66.6
                  credits: 15
                - name: Computability
                  score: 82.0
                  credits: 15
                - name: Web Programming
                  score: 79.8
                  credits: 15
            - name: Industrial Experience
              location: <a target="_blank" href="http://www.uvd.co.uk">Ultra Violet Design (UVD)</a>
              year_range: 2014/15
              score: 77.0
              weight: 7
              credits: 30
              modules:
                - name: Industrial Placement
                  score: 77.0
                  credits: 30
            - name: Second Year
              year_range: 2013/14
              score: 69.48
              weight: 28
              credits: 120
              modules:
                - name: Software Engineering
                  score: 73.4
                  credits: 15
                - name: Probability and Matrices
                  score: 59.3
                  credits: 15
                - name: Algorithms and Data Structures in an Object-Orientated Framework
                  score: 66.0
                  credits: 15
                - name: Internet Protocols and Applications
                  score: 67.4
                  credits: 15
                - name: Software Engineering Project
                  score: 94.0
                  credits: 15
                - name: Operating Systems
                  score: 64.7
                  credits: 15
                - name: Database Systems
                  score: 64.7
                  credits: 15
                - name: Graphical User Interfaces
                  score: 66.4
                  credits: 15
        - name: Hertfordshire University
          uri: http://www.herts.ac.uk
          years:
            - name: First Year
              year_range: 2012/13
              score: 89.125
              weight: 0
              credits: 120
              modules:
                - name: Programming Principles
                  score: 97.1
                  credits: 15
                - name: Foundations of Computation
                  score: 93.2
                  credits: 15
                - name: E-Media Design
                  score: 88.4
                  credits: 15
                - name: System Requirements
                  score: 83.2
                  credits: 15
                - name: Programming and Program Design
                  score: 91.4
                  credits: 15
                - name: Data Driven Systems
                  score: 87.4
                  credits: 15
                - name: Principles of Network Systems
                  score: 77.45
                  credits: 15
                - name: Internet Technologies
                  score: 88.25
                  credits: 15
                - name: Professional and Academic Skills
                  score: 73.6
                  credits: 0
